#include "init.h"

#include <Aikari-Launcher-Public/constants/itcCtrl/base.h>
#include <Aikari-Launcher-Public/constants/itcCtrl/filesystem.h>
#include <Aikari-Launcher-Public/constants/itcCtrl/network.h>
#include <Aikari-Launcher-Public/constants/lifecycle.h>
#include <Aikari-PLS-Private/types/components/seewoServiceProfile.h>
#include <Aikari-PLS/types/constants/init.h>
#include <Aikari-PLS/types/constants/msgQueue.h>
#include <Aikari-Shared/infrastructure/loggerMacro.h>
#include <Aikari-Shared/infrastructure/queue/SinglePointMessageQueue.hpp>
#include <Aikari-Shared/infrastructure/telemetryShortFn.h>
#include <Aikari-Shared/types/itc/shared.h>
#include <Aikari-Shared/utils/crypto.h>
#include <Aikari-Shared/utils/filesystem.h>
#include <Aikari-Shared/utils/string.h>
#include <Aikari-Shared/utils/windows.h>
#include <algorithm>
#include <chrono>
#include <infrastructure/threadMsgHandler.h>
#include <mbedtls/x509_crt.h>
#include <optional>

#include "components/infrastructure/config.h"
#include "components/mqtt/mqttBroker.h"
#include "components/ruleSystem/rulesManager.h"
#include "lifecycle.h"
#include "resource.h"

#define TELEMETRY_MODULE_NAME "PLS - Lifecycle - Init"
#define TELEMETRY_ACTION_CATEGORY "pls.init"

namespace plsConstants = AikariPLS::Types::Constants;

namespace itcConstants = AikariShared::Types::InterThread;

namespace AikariPLS::Init
{
    constexpr const char* hostTargetAddress = "127.11.45.14";
    constexpr const char* hostMarker =
        "# This line is generated by HugoAura-Aikari, please do not edit or "
        "delete it";
    constexpr const char* swCoreProcName = "SeewoCore.exe";

    namespace HelperFns
    {
        static void _pushSwCoreProcKilledEvent(
            AikariShared::Infrastructure::MessageQueue::SinglePointMessageQueue<
                itcConstants::SubToMainMessageInstance>* msgQueue
        )
        {
            itcConstants::SubToMainWebSocketReply wsMsg = {
                .success = true,
                .code = 0,
                .data = { { "message",
                            plsConstants::Init::NetworkInit::
                                SW_CORE_PROC_KILLED_MSG },
                          { "method",
                            plsConstants::Init::NetworkInit::
                                SW_CORE_PROC_KILLED_PUSH_METHOD } },
                .eventId = plsConstants::MsgQueue::WebSocket::WS_MSG_TYPE_PUSH,
                .wsInfo = { .isBroadcast = true }
            };

            itcConstants::SubToMainMessageInstance msgIns = {
                .type = itcConstants::MESSAGE_TYPES::WS_MESSAGE, .msg = wsMsg
            };

            msgQueue->push(msgIns);
        };

        static std::optional<std::filesystem::path> _getAikariDir(
            AikariPLS::Infrastructure::MsgQueue::PLSThreadMsgQueueHandler*
                msgQueueHandler
        )
        {
            itcConstants::SubToMainControlMessage getDirMsg = {
                .method = AikariLauncher::Public::Constants::InterThread::
                    FileSystem::Base::GET_DIR,
                .data = { { "dirType", "aikariRoot" } },
                .fromModule = plsConstants::MsgQueue::MODULE_NAME,
                .eventId =
                    AikariShared::Utils::CryptoUtils::genRandomHexInsecure(32)
            };

            auto getDirResult = msgQueueHandler->sendCtrlMsgSync(
                getDirMsg, std::chrono::milliseconds(500), true
            );

            if (!getDirResult.has_value())
            {
                LOG_ERROR("ITC timed out while trying to get Aikari dir.");
                Telemetry::addBreadcrumb(
                    "default",
                    "Failed to get reply for getAikariDirResult, itc stuck?",
                    TELEMETRY_ACTION_CATEGORY,
                    "error"
                );
                return std::nullopt;
            }

            if (!getDirResult.value().data.value("success", false))
            {
                const std::string errMsg = std::format(
                    "Failed to get Aikari DIR: ITC returns failure"
                    ". Diagnose code: {}",
                    getDirResult.value().data.value("diagnoseCode", "UNKNOWN")
                );
                LOG_ERROR(errMsg);
                Telemetry::sendEventStr(
                    SENTRY_LEVEL_ERROR, TELEMETRY_MODULE_NAME, errMsg
                );
                return std::nullopt;
            }

            std::filesystem::path aikariDir(
                static_cast<std::string>(getDirResult.value().data.at("path"))
            );

            return aikariDir;
        };

        static bool _initMqttCert(
            AikariPLS::Infrastructure::MsgQueue::PLSThreadMsgQueueHandler*
                msgQueueHandler,
            const std::filesystem::path& aikariDir,
            const std::string& hostname,
            bool forceRegen
        )
        {
#ifdef _DEBUG
            LOG_TRACE(
                "Init MQTT cert: Input Aikari DIR: {}", aikariDir.string()
            );
#endif

            const auto certPath = aikariDir / "config" / "certs" / "mqtt.crt";
            const auto keyPath = aikariDir / "config" / "certs" / "mqtt.key";

            auto certMatchesHostname =
                [](const std::filesystem::path& path,
                   const std::string& targetHost)
            {
                mbedtls_x509_crt cert;
                mbedtls_x509_crt_init(&cert);
                const int parseResult =
                    mbedtls_x509_crt_parse_file(&cert, path.string().c_str());
                if (parseResult != 0)
                {
                    mbedtls_x509_crt_free(&cert);
                    return false;
                }

                const auto* rawBegin =
                    reinterpret_cast<const char*>(cert.raw.p);
                const auto* rawEnd = rawBegin + cert.raw.len;
                const bool hostnameFound =
                    std::search(
                        rawBegin,
                        rawEnd,
                        targetHost.begin(),
                        targetHost.end()
                    ) != rawEnd;
                mbedtls_x509_crt_free(&cert);
                return hostnameFound;
            };

            if (!forceRegen && std::filesystem::exists(certPath) &&
                std::filesystem::exists(keyPath) &&
                certMatchesHostname(certPath, hostname))
            {
                LOG_INFO(
                    "MQTT TLS cert already generated for {}, skipping "
                    "regeneration...",
                    hostname
                );
                return true;
            }

            if (forceRegen)
            {
                LOG_INFO("MQTT TLS cert regeneration forced by config.");
            }
            else
            {
                LOG_INFO(
                    "MQTT TLS cert missing or SAN mismatch for {}, "
                    "regenerating...",
                    hostname
                );
            }

            itcConstants::SubToMainControlMessage initCertMsg = {
                .method = AikariLauncher::Public::Constants::InterThread::
                    Network::TLS::GEN_TLS_CERTS,
                .data = { { "baseDir",
                            (aikariDir / "config" / "certs").string() },
                          { "hostname", hostname },
                          { "identifier",
                            plsConstants::Init::NetworkInit::
                                TLS_CERT_IDENTIFIER } },
                .fromModule = plsConstants::MsgQueue::MODULE_NAME,
                .eventId =
                    AikariShared::Utils::CryptoUtils::genRandomHexInsecure(32)
            };

            auto initCertResult = msgQueueHandler->sendCtrlMsgSync(
                initCertMsg, std::chrono::milliseconds(1500), true
            );

            if (!initCertResult.has_value())
            {
                LOG_ERROR("ITC timed out while trying to init MQTT cert.");
                Telemetry::addBreadcrumb(
                    "default",
                    "Failed to get reponse for initCertResult (MQTT), itc "
                    "stuck?",
                    TELEMETRY_ACTION_CATEGORY,
                    "error"
                );
                return false;
            }

            if (!initCertResult.value().data.value("success", false))
            {
                const std::string errMsg = std::format(
                    "Failed to init MQTT cert: Error generating cert: {} | "
                    "Diagnose code: {}",
                    initCertResult.value().data.value(
                        "message", "Unknown Error"
                    ),
                    initCertResult.value().data.value("diagnoseCode", "UNKNOWN")
                );
                LOG_ERROR(errMsg);
                Telemetry::sendEventStr(
                    SENTRY_LEVEL_ERROR, TELEMETRY_MODULE_NAME, errMsg
                );
                return false;
            }

            LOG_INFO("Successfully generated MQTT TLS cert.");
            return true;
        };

        static AikariPLS::Components::Infrastructure::SeewoService::
            SeewoServiceProfile
            _buildSeewoServiceProfile(
                const AikariPLS::Types::Config::PLSCompatConfig& compatConfig
            )
        {
            auto discoveryResult = AikariPLS::Components::Infrastructure::
                SeewoService::discoverSeewoServiceProfile();
            auto profile = std::move(discoveryResult.profile);

            for (const auto& warning : discoveryResult.warnings)
            {
                LOG_WARN("SeewoService discovery warning: {}", warning);
            }

            const auto brokerOverride =
                AikariShared::Utils::String::trim(
                    compatConfig.brokerHostOverride
                );
            if (!brokerOverride.empty())
            {
                profile.brokerHost = brokerOverride;
                LOG_INFO(
                    "Using configured Seewo broker host override: {}",
                    profile.brokerHost
                );
            }

            if (compatConfig.brokerPortOverride > 0)
            {
                profile.brokerPort = compatConfig.brokerPortOverride;
            }

            LOG_INFO(
                "SeewoService profile: version={} | SeewoCore={} | "
                "ProxyLayerService={} | broker={}:{} | coreSvc={} | "
                "proxySvc={}",
                profile.version.value_or("unknown"),
                profile.seewoCorePath.has_value()
                    ? profile.seewoCorePath->string()
                    : "unknown",
                profile.proxyLayerServicePath.has_value()
                    ? profile.proxyLayerServicePath->string()
                    : "unknown",
                profile.brokerHost,
                profile.brokerPort,
                profile.seewoCoreServiceStatus,
                profile.proxyLayerServiceStatus
            );

            return profile;
        }

        static AikariLauncher::Public::Constants::Lifecycle::
            APPLICATION_RUNTIME_MODES
            _getRuntimeMode(
                AikariPLS::Infrastructure::MsgQueue::PLSThreadMsgQueueHandler*
                    msgQueueHandler
            )
        {
            itcConstants::SubToMainControlMessage getRuntimeModeMsg = {
                .method = AikariLauncher::Public::Constants::InterThread::Base::
                    Props::GET_RUNTIME_MODE,
                .data = {},
                .fromModule = plsConstants::MsgQueue::MODULE_NAME,
                .eventId =
                    AikariShared::Utils::CryptoUtils::genRandomHexInsecure(32)
            };

            auto getRuntimeModeResult = msgQueueHandler->sendCtrlMsgSync(
                getRuntimeModeMsg, std::chrono::milliseconds(500), true
            );

            if (getRuntimeModeResult.has_value())
            {
                int runtimeModeRaw =
                    (getRuntimeModeResult.value()).data.value("mode", 0);

                auto runtimeMode =
                    static_cast<AikariLauncher::Public::Constants::Lifecycle::
                                    APPLICATION_RUNTIME_MODES>(runtimeModeRaw);

                return runtimeMode;
            }
            else
            {
                LOG_WARN(
                    "Timed out getting runtime mode from launcher, considering "
                    "RUNTIME_MODES::NORMAL as default."
                );
                Telemetry::addBreadcrumb(
                    "default",
                    "Failed to get runtime mode from launcher, itc stuck?",
                    TELEMETRY_ACTION_CATEGORY,
                    "warning"
                );
                return AikariLauncher::Public::Constants::Lifecycle::
                    APPLICATION_RUNTIME_MODES::NORMAL;
            }
        };

    }  // namespace HelperFns

    AikariPLS::Types::Infrastructure::Init::PLSInitResult runPlsInit()
    {
        auto& sharedStates =
            AikariPLS::Lifecycle::PLSSharedStates::getInstance();

        auto& sharedIns =
            AikariPLS::Lifecycle::PLSSharedInsManager::getInstance();

        auto* msgQueueHandlerPtr = sharedIns.getPtr(
            &AikariPLS::Types::Lifecycle::PLSSharedIns::threadMsgQueueHandler
        );

        auto& sharedMsgQueues =
            AikariPLS::Lifecycle::PLSSharedQueuesManager::getInstance();

        auto* retMsgQueuePtr = sharedMsgQueues.getPtr(
            &AikariPLS::Types::Lifecycle::PLSSharedMsgQueues::retMsgQueue
        );

        LOG_DEBUG("Pulling Aikari runtime mode...");
        const auto runtimeMode = HelperFns::_getRuntimeMode(msgQueueHandlerPtr);
        LOG_TRACE("Runtime mode: {}", static_cast<int>(runtimeMode));
        sharedStates.setVal(
            &AikariPLS::Types::Lifecycle::PLSSharedStates::runtimeMode,
            runtimeMode
        );

        LOG_DEBUG("Getting Aikari DIR...");
        std::filesystem::path aikariRootDir;
        {
            const auto getDirResult =
                HelperFns::_getAikariDir(msgQueueHandlerPtr);
            if (getDirResult == std::nullopt)
            {
                LOG_CRITICAL("Failed to get Aikari root DIR, exiting PLS...");
                return { .isSuccess = false,
                         .message = "E_AIKARI_ROOT_DIR_GET_FAILED" };
            }
            else
            {
                aikariRootDir = getDirResult.value();
            }
        }

        HMODULE selfHModule = sharedIns.getExactVal(
            &AikariPLS::Types::Lifecycle::PLSSharedIns::hModuleIns
        );

        // ↓ Init Config Manager
        {
            auto configManagerIns = std::make_unique<
                AikariPLS::Components::Config::PLSConfigManager>(
                "pls",
                aikariRootDir / "config" / "config-pls.json",
                IDR_PLS_DEFAULT_CONF,
                selfHModule
            );
            sharedIns.setPtr(
                &AikariPLS::Types::Lifecycle::PLSSharedIns::configMgr,
                std::move(configManagerIns)
            );
        }
        auto* configManagerPtr = sharedIns.getPtr(
            &AikariPLS::Types::Lifecycle::PLSSharedIns::configMgr
        );
        bool initConfigResult = configManagerPtr->initConfig();
        if (!initConfigResult)
        {
            LOG_CRITICAL(
                "Failed to initialize config file for module PLS, exiting "
                "PLS..."
            );
            return { .isSuccess = false,
                     .message = "E_PLS_CONFIG_FILE_INIT_FAILED" };
        }
        // ↑ Init Config Manager

        auto curConfigPtr = std::atomic_load(&configManagerPtr->config);

        auto seewoProfile =
            HelperFns::_buildSeewoServiceProfile(curConfigPtr->compat);
        sharedStates.setVal(
            &AikariPLS::Types::Lifecycle::PLSSharedStates::seewoServiceProfile,
            seewoProfile
        );

        // ↓ Init Rule Scripts
        LOG_INFO("Loading rules...");
        {
            LOG_DEBUG("Getting self (DLL's) DIR...");
            auto rulePath =
                AikariShared::Utils::FileSystem::getSelfPathFromHandler(
                    selfHModule
                )
                    .parent_path() /
                "resources" / "pls" / "rules";
            nlohmann::json& ruleConfig = curConfigPtr->rules;
            auto ruleManagerIns =
                std::make_unique<AikariPLS::Components::Rules::Manager>(
                    rulePath, ruleConfig
                );
            ruleManagerIns->loadRules();
            sharedIns.setPtr(
                &AikariPLS::Types::Lifecycle::PLSSharedIns::ruleMgr,
                std::move(ruleManagerIns)
            );
        }
        // ↑ Init Rule Scripts

        // ↓ Init Hosts
        LOG_INFO("Checking hosts file entry...");
        std::vector<std::string> brokerHosts = { seewoProfile.brokerHost };
        if (curConfigPtr->compat.manageLegacyBrokerHosts)
        {
            for (const auto& host : seewoProfile.legacyBrokerHosts)
            {
                if (std::ranges::find(brokerHosts, host) == brokerHosts.end())
                {
                    brokerHosts.emplace_back(host);
                }
            }
        }
        auto hostCheckResult =
            AikariShared::Utils::Windows::Network::ensureHostKeysExist(
                hostTargetAddress, brokerHosts, hostMarker
            );
        if (hostCheckResult)
        {
            LOG_INFO("Hosts file updated, killing SeewoCore process...");
            try
            {
                AikariShared::Utils::Windows::Process::killProcessByName(
                    swCoreProcName
                );

                std::jthread pushKillEvtThread(
                    [retMsgQueuePtr]()
                    {
                        std::this_thread::sleep_for(std::chrono::seconds(2));
                        HelperFns::_pushSwCoreProcKilledEvent(retMsgQueuePtr);
                    }
                );
                pushKillEvtThread.detach();
            }
            catch (const std::exception& err)
            {
                const std::string errMsg = std::format(
                    "Failed to kill SeewoCore process | Error: {}", err.what()
                );
                LOG_ERROR(errMsg);
                Telemetry::addBreadcrumb(
                    "default", errMsg, TELEMETRY_ACTION_CATEGORY, "error"
                );
            }
        }
        // ↑ Init Hosts

        // ↓ Init MQTT TLS Env
        LOG_INFO("Ensuring MQTT TLS cert...");
        auto result = HelperFns::_initMqttCert(
            msgQueueHandlerPtr,
            aikariRootDir,
            seewoProfile.brokerHost,
            curConfigPtr->compat.forceRegenMqttCert
        );
        if (!result)
        {
            LOG_CRITICAL("Failed to init MQTT cert, exiting PLS...");
            return { .isSuccess = false, .message = "E_MQTT_CERT_INIT_FAILED" };
        }
        // ↑ Init MQTT TLS Env

        // ↓ Init MQTT Broker
        LOG_INFO("Starting MQTT Broker server...");
        LOG_DEBUG("Aikari Root DIR: {}", aikariRootDir.string());
        {
            AikariPLS::Components::MQTTBroker::BrokerLaunchArg
                brokerLaunchArg = {
                    .certPath = (aikariRootDir / "config" / "certs" /
                                 std::format(
                                     "{}.crt",
                                     plsConstants::Init::NetworkInit::
                                         TLS_CERT_IDENTIFIER
                                 ))
                                    .string(),
                    .keyPath = (aikariRootDir / "config" / "certs" /
                                std::format(
                                    "{}.key",
                                    plsConstants::Init::NetworkInit::
                                        TLS_CERT_IDENTIFIER
                                ))
                                   .string(),
                    .hostname = seewoProfile.brokerHost,
                    .port = seewoProfile.brokerPort
                };
            auto brokerIns =
                std::make_unique<AikariPLS::Components::MQTTBroker::Broker>(
                    brokerLaunchArg
                );
            sharedIns.setPtr(
                &AikariPLS::Types::Lifecycle::PLSSharedIns::mqttBroker,
                std::move(brokerIns)
            );
        }
        // ↑ Init MQTT Broker

        curConfigPtr.reset();

        return { .isSuccess = true, .message = std::nullopt };
    }
}  // namespace AikariPLS::Init
